name: catlib

on: [push, pull_request]

jobs:
  windows:
    name: CatLib test run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
      
    - name: Setup dotnet 3.x on ${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Test catlib on ${{ matrix.os }}
      run: dotnet test -c Release -s src/settings.runsettings